# Generated by Django 5.1.6 on 2025-11-14 08:52

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=users.utils.get_profile_image_path),
        ),
    ]
