# Generated by Django 5.1.6 on 2025-11-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_final_quiz'),
        ('knowledge_base', '0002_directory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='knowledge_base.directory', verbose_name='Категория'),
        ),
    ]
