# Generated by Django 5.1.6 on 2025-11-29 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_course'),
        ('knowledge_base', '0002_directory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='knowledge_base.directory', verbose_name='Категория'),
        ),
    ]
