# Generated by Django 5.1.6 on 2025-11-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Порядок урока'),
        ),
    ]
