# Generated by Django 5.1.6 on 2025-12-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_lesson_order'),
        ('quizzes', '0006_quiz_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quizzes',
            field=models.ManyToManyField(blank=True, related_name='courses', to='quizzes.quiz', verbose_name='Тесты курса'),
        ),
    ]
