# Generated by Django 5.1.6 on 2025-12-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_quizzes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.course', verbose_name='Курсы'),
        ),
    ]
