# Generated by Django 5.1.6 on 2026-01-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0011_remove_lesson_course_lesson_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='assigned_groups',
            field=models.ManyToManyField(blank=True, help_text='Пользователям из выбранных групп будет автоматически назначен этот курс', related_name='assigned_courses', to='auth.group', verbose_name='Назначить группам'),
        ),
    ]
