# Generated by Django 5.1.6 on 2025-11-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_directory_description'),
        ('quizzes', '0005_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='directory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='knowledge_base.directory', verbose_name='Категория'),
        ),
    ]
